---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.402.wtf
  resources:
  - dhcpreservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.402.wtf
  resources:
  - dhcpreservations/finalizers
  verbs:
  - update
- apiGroups:
  - networking.402.wtf
  resources:
  - dhcpreservations/status
  verbs:
  - get
  - patch
  - update
